# Generated by Django 5.1.1 on 2024-10-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_pressure_1_sessiondata_pressure_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_name',
            field=models.CharField(default='My Session', max_length=100),
        ),
    ]
