# Generated by Django 5.1.1 on 2024-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_session_session_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
